name: Check TFLint
on:
  push:
    branches:
      - "**"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Validate Terraform configuration
      uses: devops-infra/action-terraform-validate@v0.3

  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fail on malformatted files
      uses: devops-infra/action-format-hcl@v0.3
      # with:
      #   check: true

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check linting of Terraform modules
      uses: devops-infra/action-tflint@v0.3
      with:
        tflint_config: .tflint.hcl

